# config system global
resource "fortios_system_global" "global" {
  hostname     = var.hostname
  timezone     = "12"
  admintimeout = "480"
}

# config system interface
resource "fortios_system_interface" "lo0" {
  ip          = var.loopback_ip
  allowaccess = "ping https ssh snmp http telnet fgfm radius-acct probe-response fabric ftm speed-test"
  name        = "lo0"
  role        = "lan"
  type        = "loopback"
  vdom        = "root"
  mode        = "static"
  status      = "up"
}

resource "fortios_system_interface" "WAN1" {
  name        = "WAN1"
  ip          = var.wan1_ip
  speed       = "auto"
  role        = "wan"
  allowaccess = "ping"
  mode        = "static"
  type        = "vlan"
  vdom        = "root"
  vlanid      = "2002"
  interface   = "port1"
}

resource "fortios_system_interface" "WAN2" {
  name        = "WAN2"
  ip          = var.wan2_ip
  status      = "up"
  role        = "wan"
  allowaccess = "ping"
  mode        = "static"
  type        = "vlan"
  vdom        = "root"
  vlanid      = "2003"
  interface   = "port2"
}

resource "fortios_system_interface" "port3" {
  name                  = "port3"
  ip                    = var.port3_ip
  status                = "up"
  device_identification = "enable"
  speed                 = "auto"
  role                  = "lan"
  allowaccess           = "ping"
  mode                  = "static"
  type                  = "physical"
  vdom                  = "root"
  alias                 = "To-Core-DC"
}

resource "fortios_system_interface" "VPN1" {
  name          = "VPN1"
  ip            = var.vpn1.ip
  remote_ip     = var.vpn1.remote_ip
  allowaccess   = "ping"
  type          = "tunnel"
  vdom          = "root"
  interface     = "WAN1"
  autogenerated = "auto"
  status        = "up"
  depends_on    = [fortios_vpnipsec_phase1interface.VPN1_P1]
}

resource "fortios_system_interface" "VPN2" {
  name          = "VPN2"
  ip            = var.vpn2.ip
  remote_ip     = var.vpn2.remote_ip
  allowaccess   = "ping"
  type          = "tunnel"
  vdom          = "root"
  interface     = "WAN2"
  autogenerated = "auto"
  status        = "up"
  depends_on    = [fortios_vpnipsec_phase1interface.VPN2_P1]
}

resource "fortios_system_sdwan" "sdwan" {
  status = "enable"
  members {
    seq_num   = "1"
    interface = fortios_system_interface.VPN1.name
  }
  members {
    seq_num   = "2"
    interface = fortios_system_interface.VPN2.name
  }
  service {
    id        = "1"
    name      = "VPNBranches1"
    route_tag = "1"
    src {
      name = "all"
    }
    priority_members {
      seq_num = "2"
    }
  }
  service {
    id        = "2"
    name      = "VPNBranches2"
    route_tag = "2"
    src {
      name = "all"
    }
    priority_members {
      seq_num = "2"
    }
  }
  depends_on = [
    fortios_vpnipsec_phase1interface.VPN1_P1,
    fortios_vpnipsec_phase1interface.VPN2_P1,
    fortios_vpnipsec_phase2interface.VPN1_P2,
    fortios_vpnipsec_phase2interface.VPN2_P2,
    fortios_system_interface.VPN1,
    fortios_system_interface.VPN2,
    fortios_system_interface.WAN1,
    fortios_system_interface.WAN2

  ]
}

resource "fortios_system_centralmanagement" "fmg" {
    mode = "normal"
    type = "fortimanager"
    fmg = var.fmg_ip
}